INSERT 
(loan3:Loan { _id: 'loan3', amount: 400000.0, payment_method: 'Hybrid Payment' }),
(loan16:Loan { _id: 'loan16', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan18:Loan { _id: 'loan18', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan7:Loan { _id: 'loan7', amount: 327000.0, payment_method: 'Entrusted Payment' }),
(loan12:Loan { _id: 'loan12', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan9:Loan { _id: 'loan9', amount: 200000.0, payment_method: 'Entrusted Payment' }),
(loan1:Loan { _id: 'loan1', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan14:Loan { _id: 'loan14', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan5:Loan { _id: 'loan5', amount: 321859.0, payment_method: 'Entrusted Payment' }),
(loan10:Loan { _id: 'loan10', amount: 1000000.0, payment_method: 'Hybrid Payment' }),
(loan8:Loan { _id: 'loan8', amount: 200000.0, payment_method: 'Entrusted Payment' }),
(loan6:Loan { _id: 'loan6', amount: 763255.0, payment_method: 'Entrusted Payment' }),
(loan13:Loan { _id: 'loan13', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan19:Loan { _id: 'loan19', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan2:Loan { _id: 'loan2', amount: 500000.0, payment_method: 'Hybrid Payment' }),
(loan17:Loan { _id: 'loan17', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan4:Loan { _id: 'loan4', amount: 600000.0, payment_method: 'Hybrid Payment' }),
(loan11:Loan { _id: 'loan11', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan0:Loan { _id: 'loan0', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(loan15:Loan { _id: 'loan15', amount: 200000.0, payment_method: 'Hybrid Payment' }),
(account12o:Account {_id: 'account12o', balance: 0.0, name: 'Green, Guerrero and Silva' }),
(account18o:Account {_id: 'account18o', balance: 0.0, name: 'Cortez-Mullins' }),
(account16o:Account {_id: 'account16o', balance: 0.0, name: 'Nguyen Group' }),
(account10o:Account {_id: 'account10o', balance: 0.0, name: 'Smith, Watkins and Scott' }),
(account14o:Account {_id: 'account14o', balance: 0.0, name: 'Ramos, Cooper and Barker' }),
(account3i:Account {_id: 'account3i', balance: 69226.0, name: 'Meyer, Morrison and Ortiz' }),
(account5o:Account {_id: 'account5o', balance: 0.0, name: 'Burton-Adams' }),
(account16i:Account {_id: 'account16i', balance: 92859.0, name: 'Nguyen Group' }),
(account18i:Account {_id: 'account18i', balance: 35437.0, name: 'Cortez-Mullins' }),
(account1o:Account {_id: 'account1o', balance: 0.0, name: 'Mclaughlin-Wallace' }),
(account12i:Account {_id: 'account12i', balance: 14133.0, name: 'Green, Guerrero and Silva' }),
(account7i:Account {_id: 'account7i', balance: 15042.0, name: 'Sutton LLC' }),
(account9i:Account {_id: 'account9i', balance: 61693.0, name: 'Mitchell Group' }),
(account9o:Account {_id: 'account9o', balance: 0.0, name: 'Mitchell Group' }),
(account7o:Account {_id: 'account7o', balance: 0.0, name: 'Sutton LLC' }),
(account14i:Account {_id: 'account14i', balance: 97331.0, name: 'Ramos, Cooper and Barker' }),
(account1i:Account {_id: 'account1i', balance: 79625.0, name: 'Mclaughlin-Wallace' }),
(account5i:Account {_id: 'account5i', balance: 82541.0, name: 'Burton-Adams' }),
(account3o:Account {_id: 'account3o', balance: 0.0, name: 'Meyer, Morrison and Ortiz' }),
(account10i:Account {_id: 'account10i', balance: 51743.0, name: 'Smith, Watkins and Scott' }),
(account17o:Account {_id: 'account17o', balance: 0.0, name: 'Butler-Lopez' }),
(account19o:Account {_id: 'account19o', balance: 0.0, name: 'Austin Inc' }),
(account13o:Account {_id: 'account13o', balance: 0.0, name: 'Ferrell Inc' }),
(bank1:Account {_id: 'bank1', balance: 0.0, name: 'Standard Chartered Bank1' }),
(account15o:Account {_id: 'account15o', balance: 0.0, name: 'Dixon-Ritter' }),
(account11o:Account {_id: 'account11o', balance: 0.0, name: 'Morgan-Noble' }),
(account0o:Account {_id: 'account0o', balance: 0.0, name: 'Duncan-Smith' }),
(account13i:Account {_id: 'account13i', balance: 718.0, name: 'Ferrell Inc' }),
(account8i:Account {_id: 'account8i', balance: 36138.0, name: 'Koch-Johnson' }),
(account6i:Account {_id: 'account6i', balance: 84301.0, name: 'Ball, Stone and Lopez' }),
(account2i:Account {_id: 'account2i', balance: 39618.0, name: 'Miller LLC' }),
(account19i:Account {_id: 'account19i', balance: 9782.0, name: 'Austin Inc' }),
(account4o:Account {_id: 'account4o', balance: 0.0, name: 'Adams LLC' }),
(account17i:Account {_id: 'account17i', balance: 18453.0, name: 'Butler-Lopez' }),
(account4i:Account {_id: 'account4i', balance: 46371.0, name: 'Adams LLC' }),
(account2o:Account {_id: 'account2o', balance: 0.0, name: 'Miller LLC' }),
(account11i:Account {_id: 'account11i', balance: 52915.0, name: 'Morgan-Noble' }),
(account6o:Account {_id: 'account6o', balance: 0.0, name: 'Ball, Stone and Lopez' }),
(account15i:Account {_id: 'account15i', balance: 25373.0, name: 'Dixon-Ritter' }),
(account8o:Account {_id: 'account8o', balance: 0.0, name: 'Koch-Johnson' }),
(account0i:Account {_id: 'account0i', balance: 18883.0, name: 'Duncan-Smith' }),
(corp13:Corporation {_id: 'corp13', name: 'Ferrell Inc' }),
(corp19:Corporation {_id: 'corp19', name: 'Austin Inc' }),
(corp17:Corporation {_id: 'corp17', name: 'Butler-Lopez' }),
(corp11:Corporation {_id: 'corp11', name: 'Morgan-Noble' }),
(corp15:Corporation {_id: 'corp15', name: 'Dixon-Ritter' }),
(corp5:Corporation {_id: 'corp5', name: 'Burton-Adams' }),
(corp1:Corporation {_id: 'corp1', name: 'Mclaughlin-Wallace' }),
(corp9:Corporation {_id: 'corp9', name: 'Mitchell Group' }),
(corp7:Corporation {_id: 'corp7', name: 'Sutton LLC' }),
(corp3:Corporation {_id: 'corp3', name: 'Meyer, Morrison and Ortiz' }),
(corp16:Corporation {_id: 'corp16', name: 'Nguyen Group' }),
(corp18:Corporation {_id: 'corp18', name: 'Cortez-Mullins' }),
(corp12:Corporation {_id: 'corp12', name: 'Green, Guerrero and Silva' }),
(corp14:Corporation {_id: 'corp14', name: 'Ramos, Cooper and Barker' }),
(corp10:Corporation {_id: 'corp10', name: 'Smith, Watkins and Scott' }),
(corp0:Corporation {_id: 'corp0', name: 'Duncan-Smith' }),
(corp4:Corporation {_id: 'corp4', name: 'Adams LLC' }),
(corp2:Corporation {_id: 'corp2', name: 'Miller LLC' }),
(corp6:Corporation {_id: 'corp6', name: 'Ball, Stone and Lopez' }),
(corp8:Corporation {_id: 'corp8', name: 'Koch-Johnson' }),
(corp13)-[:Own]->(account13i),
(corp13)-[:Own]->(account13o),
(corp19)-[:Own]->(account19i),
(corp19)-[:Own]->(account19o),
(corp17)-[:Own]->(account17i),
(corp17)-[:Own]->(account17o),
(corp11)-[:Own]->(account11i),
(corp11)-[:Own]->(account11o),
(corp15)-[:Own]->(account15i),
(corp15)-[:Own]->(account15o),
(account3i)-[:Transfer {amount : 198601.0, time: '2024-01-01 13:00:36' }]->(account6i),
(account3i)-[:Transfer {amount : 56106.0, time: '2024-01-01 13:01:04' }]->(account6i),
(account3i)-[:Transfer {amount : 191806.0, time: '2024-01-04 13:27:14' }]->(account2i),
(corp5)-[:Own]->(account5i),
(corp5)-[:Own]->(account5o),
(loan3)-[:Transfer {amount : 400000.0, time: '2024-01-01 10:31:32' }]->(account3i),
(account16i)-[:Transfer {amount : 143325.0, time: '2024-01-06 13:43:06' }]->(account18i),
(account16i)-[:Transfer {amount : 133412.0, time: '2024-01-01 10:57:06' }]->(account19i),
(account16i)-[:Transfer {amount : 144210.0, time: '2024-01-01 13:32:50' }]->(account19i),
(account16i)-[:Transfer {amount : 157729.0, time: '2024-01-01 13:33:26' }]->(account14i),
(account16i)-[:Transfer {amount : 149933.0, time: '2024-01-01 10:35:45' }]->(account19i),
(account16i)-[:Transfer {amount : 169656.0, time: '2024-01-01 13:15:01' }]->(account19i),
(account16i)-[:Transfer {amount : 89725.0, time: '2024-01-01 13:16:11' }]->(account19i),
(account16i)-[:Transfer {amount : 89011.0, time: '2024-01-01 10:58:19' }]->(account13i),
(account16i)-[:Transfer {amount : 57371.0, time: '2024-01-05 13:31:47' }]->(account17i),
(account16i)-[:Transfer {amount : 196176.0, time: '2024-01-01 10:42:06' }]->(account17i),
(account18i)-[:Transfer {amount : 75716.0, time: '2024-01-01 10:41:18' }]->(account19i),
(account18i)-[:Transfer {amount : 90787.0, time: '2024-01-01 10:23:48' }]->(account16i),
(account18i)-[:Transfer {amount : 83209.0, time: '2024-01-01 13:32:41' }]->(account16i),
(account18i)-[:Transfer {amount : 190986.0, time: '2024-01-06 13:41:26' }]->(account17i),
(account18i)-[:Transfer {amount : 152700.0, time: '2024-01-06 13:55:44' }]->(account14i),
(account18i)-[:Transfer {amount : 80339.0, time: '2024-01-02 13:23:56' }]->(account19i),
(account12i)-[:Transfer {amount : 500000.0, time: '2024-01-01 13:40:52' }]->(account10o),
(account12i)-[:Transfer {amount : 500000.0, time: '2024-01-02 13:40:52' }]->(account10o),
(corp1)-[:Own]->(account1i),
(corp1)-[:Own]->(account1o),
(account9i)-[:Transfer {amount : 181733.0, time: '2024-01-04 13:40:05' }]->(account8i),
(account9i)-[:Transfer {amount : 186048.0, time: '2024-01-01 13:27:14' }]->(account3i),
(account14i)-[:Transfer {amount : 107450.0, time: '2024-01-01 13:41:23' }]->(account19i),
(account14i)-[:Transfer {amount : 122801.0, time: '2024-01-01 13:43:22' }]->(account19i),
(account14i)-[:Transfer {amount : 124398.0, time: '2024-01-06 13:34:53' }]->(account19i),
(corp9)-[:Own]->(account9i),
(corp9)-[:Own]->(account9o),
(corp7)-[:Own]->(account7i),
(corp7)-[:Own]->(account7o),
(corp3)-[:Own]->(account3i),
(corp3)-[:Own]->(account3o),
(loan10)-[:Transfer {amount : 1000000.0, time: '2024-01-01 10:45:53' }]->(account11i),
(corp16)-[:Own]->(account16i),
(corp16)-[:Own]->(account16o),
(corp18)-[:Own]->(account18i),
(corp18)-[:Own]->(account18o),
(corp12)-[:Own]->(account12i),
(corp12)-[:Own]->(account12o),
(corp14)-[:Own]->(account14i),
(corp14)-[:Own]->(account14o),
(corp10)-[:Related]->(corp12),
(corp10)-[:Own]->(account10i),
(corp10)-[:Own]->(account10o),
(account13i)-[:Transfer {amount : 98792.0, time: '2024-01-01 10:50:26' }]->(account16i),
(account13i)-[:Transfer {amount : 139343.0, time: '2024-01-01 13:14:12' }]->(account16i),
(account13i)-[:Transfer {amount : 59937.0, time: '2024-01-01 13:53:43' }]->(account18i),
(account13i)-[:Transfer {amount : 130716.0, time: '2024-01-01 10:34:16' }]->(account19i),
(account13i)-[:Transfer {amount : 82053.0, time: '2024-01-01 13:29:34' }]->(account19i),
(account6i)-[:Transfer {amount : 191465.0, time: '2024-01-01 13:02:31' }]->(account0i),
(corp0)-[:Own]->(account0i),
(corp0)-[:Own]->(account0o),
(loan2)-[:Transfer {amount : 500000.0, time: '2024-01-01 10:09:30' }]->(account2i),
(account2i)-[:Transfer {amount : 53264.0, time: '2024-01-01 13:36:44' }]->(account0i),
(account2i)-[:Transfer {amount : 129212.0, time: '2024-01-01 13:37:21' }]->(account0i),
(account2i)-[:Transfer {amount : 155915.0, time: '2024-01-01 13:39:12' }]->(account0i),
(corp4)-[:Own]->(account4i),
(corp4)-[:Own]->(account4o),
(account19i)-[:Transfer {amount : 53388.0, time: '2024-01-04 13:44:47' }]->(account16i),
(account19i)-[:Transfer {amount : 171486.0, time: '2024-01-01 13:41:14' }]->(account16i),
(account19i)-[:Transfer {amount : 153788.0, time: '2024-01-01 13:33:19' }]->(account17i),
(account19i)-[:Transfer {amount : 186952.0, time: '2024-01-01 13:46:55' }]->(account17i),
(account19i)-[:Transfer {amount : 121892.0, time: '2024-01-01 13:48:31' }]->(account17i),
(account19i)-[:Transfer {amount : 134451.0, time: '2024-01-01 13:40:13' }]->(account18i),
(account19i)-[:Transfer {amount : 168387.0, time: '2024-01-06 13:17:30' }]->(account14i),
(account19i)-[:Transfer {amount : 91749.0, time: '2024-01-01 13:30:29' }]->(account16i),
(account17i)-[:Transfer {amount : 52900.0, time: '2024-01-01 10:49:29' }]->(account14i),
(account17i)-[:Transfer {amount : 130900.0, time: '2024-01-01 13:40:38' }]->(account14i),
(account17i)-[:Transfer {amount : 85524.0, time: '2024-01-03 13:37:12' }]->(account15i),
(account17i)-[:Transfer {amount : 82867.0, time: '2024-01-06 13:50:20' }]->(account13i),
(account17i)-[:Transfer {amount : 62236.0, time: '2024-01-01 13:21:31' }]->(account18i),
(account17i)-[:Transfer {amount : 160958.0, time: '2024-01-01 13:23:06' }]->(account18i),
(loan4)-[:Transfer {amount : 600000.0, time: '2024-01-01 10:53:32' }]->(account4i),
(account4i)-[:Transfer {amount : 96637.0, time: '2024-01-01 13:21:59' }]->(account9i),
(account4i)-[:Transfer {amount : 163997.0, time: '2024-01-01 13:23:42' }]->(account9i),
(account4i)-[:Transfer {amount : 165317.0, time: '2024-01-01 13:25:20' }]->(account9i),
(corp2)-[:Own]->(account2i),
(corp2)-[:Own]->(account2o),
(account11i)-[:Transfer {amount : 1000000.0, time: '2024-01-01 10:45:53' }]->(account12i),
(account15i)-[:Transfer {amount : 66641.0, time: '2024-01-01 10:59:20' }]->(account19i),
(account0i)-[:Transfer {amount : 97143.0, time: '2024-01-01 13:40:05' }]->(account9i),
(account0i)-[:Transfer {amount : 111728.0, time: '2024-01-01 13:40:05' }]->(account9i),
(account0i)-[:Transfer {amount : 129594.0, time: '2024-01-03 13:02:31' }]->(account4i),
(corp6)-[:Own]->(account6i),
(corp6)-[:Own]->(account6o),
(corp8)-[:Own]->(account8i),
(corp10)-[:Apply]->(loan10),
(corp8)-[:Own]->(account8o)