// set GQL schema
SESSION SET SCHEMA /root/mySchema

// set graph 
SESSION SET PROPERTY GRAPH myGraph

// or 
SESSION SET GRAPH myGraph

// set time zone
SESSION SET TIME ZONE "+01:00"

// set a graph parameter to CURRENT_GRAPH
SESSION SET GRAPH $mainGraph = CURRENT_GRAPH

// set a graph parameter with value QueryLanguage
SESSION SET GRAPH $mainGraph = QueryLanguage

// use graph and run query
USE $mainGraph
MATCH (n) RETURN n LIMIT 10

// set a table from a query
SESSION SET TABLE $table1 = { MATCH (n:Lang) RETURN n }

// run query with the table parameter
FOR row IN $table1
LET n = row.n
RETURN COUNT(n), AVG(n.year)

// set a value
SESSION SET VALUE $query = "GQL"

// use value
MATCH (n:Lang WHERE n.name = $query) RETURN n

// set multipe parameters
SESSION SET SCHEMA /
SESSION SET $graph = QueryLanguage
SESSION SET TIME ZONE "+02:00"
SESSION SET $query = "GQL"

// reset session settings
SESSION RESET

// reset all session parameters
SESSION RESET ALL PARAMETERS

// or
SESSION RESET ALL CHARACTERISTICS

// reset schema
SESSION RESET SCHEMA

// reset graph
SESSION RESET GRAPH

// reset time zone
SESSION RESET TIME ZONE

// reset a parameter
SESSION RESET $graph

// or
SESSION RESET PARAMETER $graph

// close session
SESSION CLOSE



